services:
  - type: web
    name: django-bus-app
    env: python
    runtime: python3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DjangoProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoProject.settings
